dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: aaQUwG8yU52rEhhb7xm09Z76mi24PynZA1O9mZjXNSVRRj2XH67BgtiqEwKS8eA986sCCg34SLHTf9ucXYo73/pamsgAKLgMVeHXNvagn6TeX1EolLJqSJyo/NeiuQRIbXQwFeQvaAD2WQ21Lt9jsv4mXaVjil6tqHkiMA+0Nh5BGxqsobxXWwAA9wCfTwaM2Age07wTBrgv/tk6iRsdqi8gmf15o6bKYG4kOF20Xo78ba7a3ZjpaG8bh0XMMn4AUxhTwN0juhMvGw8wGUdN+ki1/fY/bmazlMhE5KO/Oin0TRh6hq0NMWU8CCGI+h8GZxyCA/wRw+nGItL1kFuGECN6LGm9u7FlYTQNlZB+3HAAULKbQgYxzZEAdtfQJIQORHVUNpnpPhLB5C3XLgqJAIfdUPQpNKpwfMJ+tJix/essG3sWCSQDCWpeZ6RJqD4kuXOuLYwDGFQrfEnWOE1QLM+tv7NTR50DRe/cI4ubL6FLpGk8Ht4Yn6b9jFxncVK8t8A+izd4F0aKNu0EDxJ03yTSnRb2oyb5gB8gcCkTGjGTYkChe4ydVetYPAEIKVJNFukIpyJwg7fer9gUslhZKP3aOk3TpZw/WnBe3T20gPEvLyK4P5Gy+WQtsL/Bgjqiqrg/I53YBOHvLpaEDvX4CZqs3EgqYuiVDbJTFGhKKVg=
  file: Gerbers/PIN-110_gerbers.zip
  on:
    repo: w4xzr/PIN-110
  skip_cleanup: 'true'
